language: clojure
sudo: required
services:
- docker
env:
  global:
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_70b83c40b0ba_key -iv $encrypted_70b83c40b0ba_iv -in profiles.clj.enc -out profiles.clj -d
- wget https://releases.hashicorp.com/vault/0.6.1/vault_0.6.1_linux_amd64.zip -O vault.zip
- unzip vault.zip
- export PATH=$PATH:$PWD
- ". scripts/s3-deploy-access"
- docker build -t hdf5-buildimg .

script: "./test-deploy-docker.sh"
